name: 'Reusable Playwright browser cache'
description: 'Composite action to setup playwright and caches.'
  
runs:
  using: 'composite'
  steps:
    - name: Playwright browser cache
      id: playwright-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    - name: Install with deps
      shell: bash
      run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - name: Install deps only
      shell: bash
      run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit == 'true'
