name: Create changeset PR or Release

on:
  workflow_dispatch:
  push:
    branches:
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pr-or-release:
    name: Changeset or Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node / npm env and install deps
        uses: ./.github/workflows/reusable/env-setup

      - name: Create Release Pull Request or Publish to npm if no pending changes
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          title: Upcoming package versions and changelogs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
