name: Playwright Tests
on:
  push:
    branches: [next]
  pull_request:
    branches: [next]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn
      - name: Warmup pm2
        run: yarn pm2 list
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn e2e
      - name: Cleanup
        if: always()
        run: yarn e2e:cleanup
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-results
          path: playwright-results/
          retention-days: 30
