name: Release and Publish

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-and-publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node / npm env and install deps
        uses: ./.github/workflows/reusable/env-setup

      - name: Config git
        run: |
          git config --global user.name "Github Actions Releaser"
          git config --global user.email "devtools@neo4j.com"

      - name: Version and release
        run: npm run release

      - name: Publish
        run: npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Push tag and changes to GitHub
        run: git push && git push --tags
